language: node_js

node_js:
   - '12'

branches:
   only:
      - master

before_install:
   - npm update

install:
   - npm install -g codecov

script:
   - npm test
   - codecov

sudo: false

cache:
   npm: true
   directories:
      - node_modules
